/**
* @File Name : Planification_ControllerTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 7, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 7, 2024 |   | Initial Version
**/
@IsTest
public class Planification_ControllerTest {
	 @IsTest
    public static void fake_method(){
        Planification_Controller.fake_method();
    }
}